select 
    NATION.N_NAME,
    count(ORDERS.O_ORDERKEY) as PEDIDOS     
from ORDERS 
join CUSTOMER 
    on ORDERS.O_CUSTKEY = CUSTOMER.C_CUSTKEY 
join NATION 
    on CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY 
group by NATION.N_NAME 
order by PEDIDOS desc;